# Generated by Django 4.2.2 on 2023-07-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20200722_0405"),
    ]

    operations = [
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("decline", "Decline"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("bulk", "Bulk"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.buyer",
                    ),
                ),
                (
                    "drop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.drop",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.season",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.supplier"
                    ),
                ),
            ],
        ),
    ]
