# Generated by Django 4.2.2 on 2023-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editor_name", models.CharField(max_length=200)),
                ("num_users", models.IntegerField()),
            ],
        ),
    ]
